import { describe, it, expect, beforeAll } from 'vitest';
import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const cli = join(root, 'dist', 'cli.js');

interface RunResult {
  stdout: string;
  status: number;
}

const run = (args: string[], input: string): RunResult => {
  try {
    const stdout = execFileSync('node', [cli, ...args], { input, encoding: 'utf8', stdio: ['pipe', 'pipe', 'ignore'] });
    return { stdout, status: 0 };
  } catch (e) {
    const err = e as { stdout?: string; status?: number };
    return { stdout: err.stdout ?? '', status: err.status ?? 1 };
  }
};

describe('CLI', () => {
  beforeAll(() => {
    // The CLI tests run against the built binary; build it if missing.
    if (!existsSync(cli)) {
      execFileSync('npm', ['run', 'build'], { cwd: root, stdio: 'ignore' });
    }
  }, 120_000);

  it('--json emits a ConversionResult with all four keys', () => {
    const { stdout } = run(['--json'], "module.exports = { entry: './src/index.js' };");
    const parsed = JSON.parse(stdout);
    expect(Object.keys(parsed).sort()).toEqual(['dependencies', 'flags', 'output', 'warnings']);
    expect(parsed.flags.targetViteMajor).toBe(8);
    expect(parsed.output).toContain('rolldownOptions');
  });

  it('--json --target-vite 7 switches the bundler option key', () => {
    const { stdout } = run(['--json', '--target-vite', '7'], "module.exports = { entry: './src/index.js' };");
    const parsed = JSON.parse(stdout);
    expect(parsed.flags.targetViteMajor).toBe(7);
    expect(parsed.output).toContain('rollupOptions: {');
  });

  it('--strict exits non-zero when a manual warning exists', () => {
    const { status } = run(['--strict', '--quiet'], "module.exports = { externals: { react: 'React' } };");
    expect(status).toBe(1);
  });

  it('--strict exits zero for an info-only config', () => {
    const { status } = run(['--strict', '--quiet'], "module.exports = { mode: 'production' };");
    expect(status).toBe(0);
  });

  it('writes a config skeleton to stdout by default', () => {
    const { stdout, status } = run([], "module.exports = { mode: 'production' };");
    expect(status).toBe(0);
    expect(stdout).toContain('export default defineConfig({');
    expect(stdout).toContain('// Generated by @shiftkit/webpack-to-vite');
  });
});
