/**
 * Render the intermediate ViteModel to a vite.config.ts skeleton.
 *
 * Default output is Vite 8-first: build.rolldownOptions, built-in
 * resolve.tsconfigPaths. With targetViteMajor: 7 it emits build.rollupOptions
 * and swaps the built-in tsconfig paths resolution for the vite-tsconfig-paths
 * plugin.
 */
import type { ViteModel } from './types.js';

const HEADER = [
  '// Generated by @shiftkit/webpack-to-vite',
  '// Migration Analyzer output: review warnings before merging.',
  '// This file was generated without executing your webpack config.',
];

const VITE8_NOTE = [
  '// Vite 8 note:',
  '// - build.rollupOptions was renamed to build.rolldownOptions.',
  '// - build.commonjsOptions is a no-op.',
  '// - object-form manualChunks was removed; use Rolldown codeSplitting.',
];

export function render(model: ViteModel, target: 7 | 8): string {
  const imports = new Set<string>(["import { defineConfig } from 'vite';"]);
  for (const imp of model.imports) imports.add(imp);

  const plugins = [...model.plugins];

  // tsconfig paths: built-in for Vite 8, plugin for Vite 7.
  const wantsTsconfigPaths = model.resolve.tsconfigPaths === true;
  const emitTsconfigPathsOption = wantsTsconfigPaths && target === 8;
  if (wantsTsconfigPaths && target === 7) {
    imports.add("import tsconfigPaths from 'vite-tsconfig-paths';");
    if (!plugins.includes('tsconfigPaths()')) plugins.unshift('tsconfigPaths()');
  }

  const lines: string[] = [];
  lines.push(...HEADER, '');
  lines.push(...sortImports(imports), '');
  lines.push('export default defineConfig({');

  if (plugins.length > 0) {
    lines.push(`  plugins: [${plugins.join(', ')}],`);
  }

  if (model.publicDir != null) {
    lines.push(`  publicDir: ${model.publicDir}, // from devServer.static/contentBase — files served as-is at '/'`);
  }

  renderResolve(lines, model, emitTsconfigPathsOption);
  renderDefine(lines, model);
  renderCss(lines, model);
  renderServer(lines, model);
  if (model.build.base != null) {
    lines.push(`  base: ${model.build.base}, // from output.publicPath — verify your deploy sub-path`);
  }
  renderBuild(lines, model, target);

  lines.push('});');

  if (model.vite8NoteNeeded && target === 8) {
    lines.push('', ...VITE8_NOTE);
  }

  return lines.join('\n');
}

function sortImports(imports: Set<string>): string[] {
  const arr = [...imports];
  // Keep the `vite` import first; sort the rest for stable output.
  const head = arr.filter((i) => i.includes("from 'vite'") && i.includes('defineConfig'));
  const rest = arr.filter((i) => !(i.includes("from 'vite'") && i.includes('defineConfig'))).sort();
  return [...head, ...rest];
}

function renderResolve(lines: string[], model: ViteModel, tsconfigPaths: boolean): void {
  const { alias, extensions } = model.resolve;
  if (!tsconfigPaths && alias.length === 0 && (!extensions || extensions.length === 0)) return;

  lines.push('  resolve: {');
  if (tsconfigPaths) lines.push('    tsconfigPaths: true,');
  if (alias.length > 0) {
    lines.push('    alias: [');
    for (const a of alias) lines.push(`      { find: ${a.find}, replacement: ${a.replacement} },`);
    lines.push('    ],');
  }
  if (extensions && extensions.length > 0) {
    const exts = extensions.map((e) => `'${e.startsWith('.') ? e : `.${e}`}'`).join(', ');
    lines.push(`    extensions: [${exts}],`);
  }
  lines.push('  },');
}

function renderDefine(lines: string[], model: ViteModel): void {
  if (model.define.size === 0) return;
  lines.push('  define: {');
  for (const [key, entry] of model.define) {
    const comment = entry.comment ? ` // ${entry.comment}` : '';
    lines.push(`    ${key}: ${entry.value},${comment}`);
  }
  lines.push('  },');
}

/**
 * Build a ready-to-paste index.html skeleton from the statically-read
 * HtmlWebpackPlugin options plus the detected entry. Vite serves index.html
 * from the project root; the module script tag replaces the webpack entry.
 */
export function buildIndexHtml(model: ViteModel): string {
  const html = model.htmlPlugin ?? {};
  const entry = model.entryPaths[0];
  const src = entry ? `/${entry.replace(/^\.\//, '')}` : '/src/main.js';
  const title = html.title ?? 'App';
  const favicon = html.favicon ? `/${html.favicon.replace(/^\.\//, '')}` : null;

  const lines: string[] = [
    '<!doctype html>',
    '<html lang="en">',
    '  <head>',
    '    <meta charset="UTF-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  ];
  if (favicon) lines.push(`    <link rel="icon" href="${favicon}" />`);
  lines.push(`    <title>${escapeHtml(title)}</title>`);
  if (html.template) {
    lines.push(`    <!-- Generated by @shiftkit/webpack-to-vite from HtmlWebpackPlugin (template: ${html.template}).`);
    lines.push('         Merge any meta tags / template markup from that file, then delete this comment. -->');
  } else {
    lines.push('    <!-- Generated by @shiftkit/webpack-to-vite from HtmlWebpackPlugin. -->');
  }
  lines.push(
    '  </head>',
    '  <body>',
    '    <div id="root"></div>',
    ...(entry
      ? [`    <script type="module" src="${src}"></script>`]
      : [
          `    <!-- TODO: no static webpack entry was detected — point this at your entry module. -->`,
          `    <script type="module" src="${src}"></script>`,
        ]),
    '  </body>',
    '</html>',
    ''
  );
  return lines.join('\n');
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function renderCss(lines: string[], model: ViteModel): void {
  if (model.cssPreprocessorOptions.size === 0) return;
  lines.push('  css: {');
  lines.push('    preprocessorOptions: {');
  for (const [lang, options] of model.cssPreprocessorOptions) {
    lines.push(`      ${lang}: {`);
    for (const [key, value] of options) {
      lines.push(`        ${key}: ${value},`);
    }
    lines.push('      },');
  }
  lines.push('    },');
  lines.push('  },');
}

function renderServer(lines: string[], model: ViteModel): void {
  const { host, port, open, https, proxy } = model.server;
  if (host == null && port == null && open == null && https == null && proxy == null) return;

  lines.push('  server: {');
  if (host != null) lines.push(`    host: ${host},`);
  if (port != null) lines.push(`    port: ${port},`);
  if (open != null) lines.push(`    open: ${open},`);
  if (https != null) lines.push(`    https: ${https},`);
  if (proxy != null) lines.push(`    proxy: ${proxy},`);
  lines.push('  },');
}

function renderBuild(lines: string[], model: ViteModel, target: 7 | 8): void {
  const b = model.build;
  const optsKey = target === 8 ? 'rolldownOptions' : 'rollupOptions';
  // A library build consumes the entry: it moves into build.lib.entry instead
  // of the bundler input.
  const bundlerInput = b.lib ? null : b.input ?? null;
  const hasBundlerOpts =
    bundlerInput != null || b.entryFileNames != null || b.chunkFileNames != null || b.codeSplittingNote === true;
  const hasBuild =
    b.outDir != null || b.sourcemap != null || b.lib != null || hasBundlerOpts || model.buildNotes.length > 0;
  if (!hasBuild) return;

  lines.push('  build: {');
  if (b.outDir != null) lines.push(`    outDir: ${b.outDir},`);
  if (b.sourcemap != null) lines.push(`    sourcemap: ${b.sourcemap},`);
  if (b.lib != null) {
    lines.push('    lib: { // from output.library/libraryTarget — verify entry, formats, and fileName');
    lines.push(
      b.input != null
        ? `      entry: ${b.input},`
        : `      entry: 'src/index.ts', // TODO: no static webpack entry was detected — set your library entry`
    );
    if (b.lib.name != null) lines.push(`      name: ${b.lib.name},`);
    if (b.lib.formats && b.lib.formats.length > 0) {
      lines.push(`      formats: [${b.lib.formats.map((f) => `'${f}'`).join(', ')}],`);
    }
    lines.push('    },');
  }
  for (const note of model.buildNotes) lines.push(`    ${note}`);

  if (hasBundlerOpts) {
    lines.push(`    ${optsKey}: {`);
    if (bundlerInput != null) lines.push(`      input: ${bundlerInput},`);
    if (b.entryFileNames != null || b.chunkFileNames != null) {
      lines.push('      // Output naming differs from webpack ([name]/[contenthash] tokens). Verify before relying on exact names:');
      lines.push('      // output: {');
      if (b.entryFileNames != null) lines.push(`      //   entryFileNames: ${b.entryFileNames}, // from output.filename`);
      if (b.chunkFileNames != null) lines.push(`      //   chunkFileNames: ${b.chunkFileNames}, // from output.chunkFilename`);
      lines.push('      // },');
    }
    if (b.codeSplittingNote === true) {
      lines.push(
        target === 8
          ? '      // splitChunks → configure Rolldown codeSplitting here if you need manual chunk grouping.'
          : '      // splitChunks → configure output.manualChunks here if you need manual chunk grouping.'
      );
    }
    lines.push('    },');
  }

  lines.push('  },');
}
